'use strict';


function processData(input) {
    var parse_fun = function (s) { return parseInt(s, 10); };

    var lines = input.split('\n');
    var T = parse_fun(lines.shift());

    var data = lines.splice(0, T).map(parse_fun);

    // logic here
    // The input variable below is in the same format provided by HackerRank
    // var input = "3\n0\n1\n4"

    // Create a variable named splitInput
    // Split the input variable on the '\n' character
    var splitInput = input.split("\n"),

    // Log the result of the splutInput variable
    // console.log(splitInput)

    // Create a variable named numberOfTestCases
    // Assign numberOfTestCases to be the first index of the splitInput variable
    // Remove the first index of the splitInput variable
        numberOfTestCases = splitInput.splice(0,1),

    // Log the result of the numberOfTestCases variable
    // console.log(numberOfTestCases)

    // Log the result of the splitInput variable
    // console.log(splitInput)

    // Create a variable named height
        height;

    // Create a function named add to increment the height by one meter
    var add = function add () {
        return height += 1;
    }

    // Create a function named double to double the current value of the height variable
    var double = function double () {
        return height = height * 2;
    }

    // Create a function named calculate that accepts a number of test cases (n) as a parameter
    var calculate = function calculate (n) {
        // Perform a number of iterations on the height variable equal to the number of test cases
        for (var i = 0; i <= n; i++) {
            if (i === 0) {
                // If it is the first test case, set the height to one meter
                height = 1;
            } else if (i % 2 === 0) {
                // If the test case number is even, call the add function
                add();
            } else if (i % 2 !== 0) {
                // If the test case number is odd, call the double function
                double();
            }
        }
        // Return the value of the height variable
        return height;
    }

    // Create an array named results to store the calculated values generated by the calculate function
    var results = [];

    // Iterate through the splitInput array
    for (var i = 0; i < splitInput.length; i++) {
        // Call the calculate function on each index of the splitInput array
        // Push each result from the calculate function into the results array
        results.push(calculate(splitInput[i]));
    }

    // Log the results array
    // console.log(results)

    // Create a string variable named joinedResults
    // The joinedResults variable is the result of joining the results array on the '\n' character
    var joinedResults = results.join("\n");

    // Log the joinedResults variable
    // console.log(joinedResults)

    // Write the joinedResults to pass the HackerRank test
    process.stdout.write(joinedResults);

}

process.stdin.resume();
process.stdin.setEncoding("ascii");
var _input = "";
process.stdin.on("data", function (input) { _input += input; });
process.stdin.on("end", function () { processData(_input); });